#![allow(nonstandard_style)]

use std::ops::Deref;

use capstone::{
    Capstone,
    arch::{self, BuildsCapstone},
};
use strum_macros::{AsRefStr, Display, EnumIter, EnumString};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, EnumString, Display, AsRefStr, EnumIter)]
#[strum(serialize_all = "lowercase")]
pub enum X86Register {
    INVALID,
    AH,
    AL,
    AX,
    BH,
    BL,
    BP,
    BPL,
    BX,
    CH,
    CL,
    CS,
    CX,
    DH,
    DI,
    DIL,
    DL,
    DS,
    DX,
    EAX,
    EBP,
    EBX,
    ECX,
    EDI,
    EDX,
    EFLAGS,
    EIP,
    ES,
    ESI,
    ESP,
    FPSW,
    FS,
    GS,
    IP,
    RAX,
    RBP,
    RBX,
    RCX,
    RDI,
    RDX,
    RIP,
    RSI,
    RSP,
    SI,
    SIL,
    SP,
    SPL,
    SS,
    CR0,
    CR1,
    CR2,
    CR3,
    CR4,
    CR8,
    DR0,
    DR1,
    DR2,
    DR3,
    DR4,
    DR5,
    DR6,
    DR7,
    FP0,
    FP1,
    FP2,
    FP3,
    FP4,
    FP5,
    FP6,
    FP7,
    K0,
    K1,
    K2,
    K3,
    K4,
    K5,
    K6,
    K7,
    MM0,
    MM1,
    MM2,
    MM3,
    MM4,
    MM5,
    MM6,
    MM7,
    R8,
    R9,
    R10,
    R11,
    R12,
    R13,
    R14,
    R15,
    ST0,
    ST1,
    ST2,
    ST3,
    ST4,
    ST5,
    ST6,
    ST7,
    XMM0,
    XMM1,
    XMM2,
    XMM3,
    XMM4,
    XMM5,
    XMM6,
    XMM7,
    XMM8,
    XMM9,
    XMM10,
    XMM11,
    XMM12,
    XMM13,
    XMM14,
    XMM15,
    XMM16,
    XMM17,
    XMM18,
    XMM19,
    XMM20,
    XMM21,
    XMM22,
    XMM23,
    XMM24,
    XMM25,
    XMM26,
    XMM27,
    XMM28,
    XMM29,
    XMM30,
    XMM31,
    YMM0,
    YMM1,
    YMM2,
    YMM3,
    YMM4,
    YMM5,
    YMM6,
    YMM7,
    YMM8,
    YMM9,
    YMM10,
    YMM11,
    YMM12,
    YMM13,
    YMM14,
    YMM15,
    YMM16,
    YMM17,
    YMM18,
    YMM19,
    YMM20,
    YMM21,
    YMM22,
    YMM23,
    YMM24,
    YMM25,
    YMM26,
    YMM27,
    YMM28,
    YMM29,
    YMM30,
    YMM31,
    ZMM0,
    ZMM1,
    ZMM2,
    ZMM3,
    ZMM4,
    ZMM5,
    ZMM6,
    ZMM7,
    ZMM8,
    ZMM9,
    ZMM10,
    ZMM11,
    ZMM12,
    ZMM13,
    ZMM14,
    ZMM15,
    ZMM16,
    ZMM17,
    ZMM18,
    ZMM19,
    ZMM20,
    ZMM21,
    ZMM22,
    ZMM23,
    ZMM24,
    ZMM25,
    ZMM26,
    ZMM27,
    ZMM28,
    ZMM29,
    ZMM30,
    ZMM31,
    R8B,
    R9B,
    R10B,
    R11B,
    R12B,
    R13B,
    R14B,
    R15B,
    R8D,
    R9D,
    R10D,
    R11D,
    R12D,
    R13D,
    R14D,
    R15D,
    R8W,
    R9W,
    R10W,
    R11W,
    R12W,
    R13W,
    R14W,
    R15W,
    IDTR,
    GDTR,
    LDTR,
    TR,
    FPCW,
    FPTAG,
    MSR,
    MXCSR,
    FS_BASE,
    GS_BASE,
    FLAGS,
    RFLAGS,
    FIP,
    FCS,
    FDP,
    FDS,
    FOP,
    ENDING,

    /// Flag registers
    OF,
    SF,
    ZF,
    AF,
    CF,
    PF,
    TF,
    IF,
    DF,
    IOPL,
    NT,
    MD,
    RF,
    VM,
    AC,
    VIF,
    VIP,
    ID,
    AI,
}

impl TryFrom<capstone::RegId> for X86Register {
    type Error = String;

    fn try_from(rid: capstone::RegId) -> Result<Self, Self::Error> {
        let cs = Capstone::new()
            .x86()
            .mode(arch::x86::ArchMode::Mode64)
            .detail(true)
            .build()
            .map_err(|e| format!("Failed to build Capstone: {}", e))?;
        let capstone_name = cs.reg_name(rid).unwrap_or("invalid".into());
        capstone_name
            .parse()
            .map_err(|_| "Failed to parse RegisterX86".to_string())
    }
}

impl TryFrom<unicorn_engine::RegisterX86> for X86Register {
    type Error = String;

    fn try_from(ureg: unicorn_engine::RegisterX86) -> Result<Self, Self::Error> {
        let reg_str = format!("{:?}", ureg);
        reg_str
            .parse()
            .map_err(|_| "Failed to parse RegisterX86".to_string())
    }
}

/// wrapper to convert X86Register to unicorn_engine::RegisterX86
pub struct UCX86Register(unicorn_engine::RegisterX86);

impl From<&X86Register> for UCX86Register {
    fn from(reg: &X86Register) -> Self {
        match reg {
            X86Register::INVALID => UCX86Register(unicorn_engine::RegisterX86::INVALID),
            X86Register::AH => UCX86Register(unicorn_engine::RegisterX86::AH),
            X86Register::AL => UCX86Register(unicorn_engine::RegisterX86::AL),
            X86Register::AX => UCX86Register(unicorn_engine::RegisterX86::AX),
            X86Register::BH => UCX86Register(unicorn_engine::RegisterX86::BH),
            X86Register::BL => UCX86Register(unicorn_engine::RegisterX86::BL),
            X86Register::BP => UCX86Register(unicorn_engine::RegisterX86::BP),
            X86Register::BPL => UCX86Register(unicorn_engine::RegisterX86::BPL),
            X86Register::BX => UCX86Register(unicorn_engine::RegisterX86::BX),
            X86Register::CH => UCX86Register(unicorn_engine::RegisterX86::CH),
            X86Register::CL => UCX86Register(unicorn_engine::RegisterX86::CL),
            X86Register::CS => UCX86Register(unicorn_engine::RegisterX86::CS),
            X86Register::CX => UCX86Register(unicorn_engine::RegisterX86::CX),
            X86Register::DH => UCX86Register(unicorn_engine::RegisterX86::DH),
            X86Register::DI => UCX86Register(unicorn_engine::RegisterX86::DI),
            X86Register::DIL => UCX86Register(unicorn_engine::RegisterX86::DIL),
            X86Register::DL => UCX86Register(unicorn_engine::RegisterX86::DL),
            X86Register::DS => UCX86Register(unicorn_engine::RegisterX86::DS),
            X86Register::DX => UCX86Register(unicorn_engine::RegisterX86::DX),
            X86Register::EAX => UCX86Register(unicorn_engine::RegisterX86::EAX),
            X86Register::EBP => UCX86Register(unicorn_engine::RegisterX86::EBP),
            X86Register::EBX => UCX86Register(unicorn_engine::RegisterX86::EBX),
            X86Register::ECX => UCX86Register(unicorn_engine::RegisterX86::ECX),
            X86Register::EDI => UCX86Register(unicorn_engine::RegisterX86::EDI),
            X86Register::EDX => UCX86Register(unicorn_engine::RegisterX86::EDX),
            X86Register::EFLAGS => UCX86Register(unicorn_engine::RegisterX86::EFLAGS),
            X86Register::EIP => UCX86Register(unicorn_engine::RegisterX86::EIP),
            X86Register::ES => UCX86Register(unicorn_engine::RegisterX86::ES),
            X86Register::ESI => UCX86Register(unicorn_engine::RegisterX86::ESI),
            X86Register::ESP => UCX86Register(unicorn_engine::RegisterX86::ESP),
            X86Register::FPSW => UCX86Register(unicorn_engine::RegisterX86::FPSW),
            X86Register::FS => UCX86Register(unicorn_engine::RegisterX86::FS),
            X86Register::GS => UCX86Register(unicorn_engine::RegisterX86::GS),
            X86Register::IP => UCX86Register(unicorn_engine::RegisterX86::IP),
            X86Register::RAX => UCX86Register(unicorn_engine::RegisterX86::RAX),
            X86Register::RBP => UCX86Register(unicorn_engine::RegisterX86::RBP),
            X86Register::RBX => UCX86Register(unicorn_engine::RegisterX86::RBX),
            X86Register::RCX => UCX86Register(unicorn_engine::RegisterX86::RCX),
            X86Register::RDI => UCX86Register(unicorn_engine::RegisterX86::RDI),
            X86Register::RDX => UCX86Register(unicorn_engine::RegisterX86::RDX),
            X86Register::RIP => UCX86Register(unicorn_engine::RegisterX86::RIP),
            X86Register::RSI => UCX86Register(unicorn_engine::RegisterX86::RSI),
            X86Register::RSP => UCX86Register(unicorn_engine::RegisterX86::RSP),
            X86Register::SI => UCX86Register(unicorn_engine::RegisterX86::SI),
            X86Register::SIL => UCX86Register(unicorn_engine::RegisterX86::SIL),
            X86Register::SP => UCX86Register(unicorn_engine::RegisterX86::SP),
            X86Register::SPL => UCX86Register(unicorn_engine::RegisterX86::SPL),
            X86Register::SS => UCX86Register(unicorn_engine::RegisterX86::SS),
            X86Register::CR0 => UCX86Register(unicorn_engine::RegisterX86::CR0),
            X86Register::CR1 => UCX86Register(unicorn_engine::RegisterX86::CR1),
            X86Register::CR2 => UCX86Register(unicorn_engine::RegisterX86::CR2),
            X86Register::CR3 => UCX86Register(unicorn_engine::RegisterX86::CR3),
            X86Register::CR4 => UCX86Register(unicorn_engine::RegisterX86::CR4),
            X86Register::CR8 => UCX86Register(unicorn_engine::RegisterX86::CR8),
            X86Register::DR0 => UCX86Register(unicorn_engine::RegisterX86::DR0),
            X86Register::DR1 => UCX86Register(unicorn_engine::RegisterX86::DR1),
            X86Register::DR2 => UCX86Register(unicorn_engine::RegisterX86::DR2),
            X86Register::DR3 => UCX86Register(unicorn_engine::RegisterX86::DR3),
            X86Register::DR4 => UCX86Register(unicorn_engine::RegisterX86::DR4),
            X86Register::DR5 => UCX86Register(unicorn_engine::RegisterX86::DR5),
            X86Register::DR6 => UCX86Register(unicorn_engine::RegisterX86::DR6),
            X86Register::DR7 => UCX86Register(unicorn_engine::RegisterX86::DR7),
            X86Register::FP0 => UCX86Register(unicorn_engine::RegisterX86::FP0),
            X86Register::FP1 => UCX86Register(unicorn_engine::RegisterX86::FP1),
            X86Register::FP2 => UCX86Register(unicorn_engine::RegisterX86::FP2),
            X86Register::FP3 => UCX86Register(unicorn_engine::RegisterX86::FP3),
            X86Register::FP4 => UCX86Register(unicorn_engine::RegisterX86::FP4),
            X86Register::FP5 => UCX86Register(unicorn_engine::RegisterX86::FP5),
            X86Register::FP6 => UCX86Register(unicorn_engine::RegisterX86::FP6),
            X86Register::FP7 => UCX86Register(unicorn_engine::RegisterX86::FP7),
            X86Register::K0 => UCX86Register(unicorn_engine::RegisterX86::K0),
            X86Register::K1 => UCX86Register(unicorn_engine::RegisterX86::K1),
            X86Register::K2 => UCX86Register(unicorn_engine::RegisterX86::K2),
            X86Register::K3 => UCX86Register(unicorn_engine::RegisterX86::K3),
            X86Register::K4 => UCX86Register(unicorn_engine::RegisterX86::K4),
            X86Register::K5 => UCX86Register(unicorn_engine::RegisterX86::K5),
            X86Register::K6 => UCX86Register(unicorn_engine::RegisterX86::K6),
            X86Register::K7 => UCX86Register(unicorn_engine::RegisterX86::K7),
            X86Register::MM0 => UCX86Register(unicorn_engine::RegisterX86::MM0),
            X86Register::MM1 => UCX86Register(unicorn_engine::RegisterX86::MM1),
            X86Register::MM2 => UCX86Register(unicorn_engine::RegisterX86::MM2),
            X86Register::MM3 => UCX86Register(unicorn_engine::RegisterX86::MM3),
            X86Register::MM4 => UCX86Register(unicorn_engine::RegisterX86::MM4),
            X86Register::MM5 => UCX86Register(unicorn_engine::RegisterX86::MM5),
            X86Register::MM6 => UCX86Register(unicorn_engine::RegisterX86::MM6),
            X86Register::MM7 => UCX86Register(unicorn_engine::RegisterX86::MM7),
            X86Register::R8 => UCX86Register(unicorn_engine::RegisterX86::R8),
            X86Register::R9 => UCX86Register(unicorn_engine::RegisterX86::R9),
            X86Register::R10 => UCX86Register(unicorn_engine::RegisterX86::R10),
            X86Register::R11 => UCX86Register(unicorn_engine::RegisterX86::R11),
            X86Register::R12 => UCX86Register(unicorn_engine::RegisterX86::R12),
            X86Register::R13 => UCX86Register(unicorn_engine::RegisterX86::R13),
            X86Register::R14 => UCX86Register(unicorn_engine::RegisterX86::R14),
            X86Register::R15 => UCX86Register(unicorn_engine::RegisterX86::R15),
            X86Register::ST0 => UCX86Register(unicorn_engine::RegisterX86::ST0),
            X86Register::ST1 => UCX86Register(unicorn_engine::RegisterX86::ST1),
            X86Register::ST2 => UCX86Register(unicorn_engine::RegisterX86::ST2),
            X86Register::ST3 => UCX86Register(unicorn_engine::RegisterX86::ST3),
            X86Register::ST4 => UCX86Register(unicorn_engine::RegisterX86::ST4),
            X86Register::ST5 => UCX86Register(unicorn_engine::RegisterX86::ST5),
            X86Register::ST6 => UCX86Register(unicorn_engine::RegisterX86::ST6),
            X86Register::ST7 => UCX86Register(unicorn_engine::RegisterX86::ST7),
            X86Register::XMM0 => UCX86Register(unicorn_engine::RegisterX86::XMM0),
            X86Register::XMM1 => UCX86Register(unicorn_engine::RegisterX86::XMM1),
            X86Register::XMM2 => UCX86Register(unicorn_engine::RegisterX86::XMM2),
            X86Register::XMM3 => UCX86Register(unicorn_engine::RegisterX86::XMM3),
            X86Register::XMM4 => UCX86Register(unicorn_engine::RegisterX86::XMM4),
            X86Register::XMM5 => UCX86Register(unicorn_engine::RegisterX86::XMM5),
            X86Register::XMM6 => UCX86Register(unicorn_engine::RegisterX86::XMM6),
            X86Register::XMM7 => UCX86Register(unicorn_engine::RegisterX86::XMM7),
            X86Register::XMM8 => UCX86Register(unicorn_engine::RegisterX86::XMM8),
            X86Register::XMM9 => UCX86Register(unicorn_engine::RegisterX86::XMM9),
            X86Register::XMM10 => UCX86Register(unicorn_engine::RegisterX86::XMM10),
            X86Register::XMM11 => UCX86Register(unicorn_engine::RegisterX86::XMM11),
            X86Register::XMM12 => UCX86Register(unicorn_engine::RegisterX86::XMM12),
            X86Register::XMM13 => UCX86Register(unicorn_engine::RegisterX86::XMM13),
            X86Register::XMM14 => UCX86Register(unicorn_engine::RegisterX86::XMM14),
            X86Register::XMM15 => UCX86Register(unicorn_engine::RegisterX86::XMM15),
            X86Register::XMM16 => UCX86Register(unicorn_engine::RegisterX86::XMM16),
            X86Register::XMM17 => UCX86Register(unicorn_engine::RegisterX86::XMM17),
            X86Register::XMM18 => UCX86Register(unicorn_engine::RegisterX86::XMM18),
            X86Register::XMM19 => UCX86Register(unicorn_engine::RegisterX86::XMM19),
            X86Register::XMM20 => UCX86Register(unicorn_engine::RegisterX86::XMM20),
            X86Register::XMM21 => UCX86Register(unicorn_engine::RegisterX86::XMM21),
            X86Register::XMM22 => UCX86Register(unicorn_engine::RegisterX86::XMM22),
            X86Register::XMM23 => UCX86Register(unicorn_engine::RegisterX86::XMM23),
            X86Register::XMM24 => UCX86Register(unicorn_engine::RegisterX86::XMM24),
            X86Register::XMM25 => UCX86Register(unicorn_engine::RegisterX86::XMM25),
            X86Register::XMM26 => UCX86Register(unicorn_engine::RegisterX86::XMM26),
            X86Register::XMM27 => UCX86Register(unicorn_engine::RegisterX86::XMM27),
            X86Register::XMM28 => UCX86Register(unicorn_engine::RegisterX86::XMM28),
            X86Register::XMM29 => UCX86Register(unicorn_engine::RegisterX86::XMM29),
            X86Register::XMM30 => UCX86Register(unicorn_engine::RegisterX86::XMM30),
            X86Register::XMM31 => UCX86Register(unicorn_engine::RegisterX86::XMM31),
            X86Register::YMM0 => UCX86Register(unicorn_engine::RegisterX86::YMM0),
            X86Register::YMM1 => UCX86Register(unicorn_engine::RegisterX86::YMM1),
            X86Register::YMM2 => UCX86Register(unicorn_engine::RegisterX86::YMM2),
            X86Register::YMM3 => UCX86Register(unicorn_engine::RegisterX86::YMM3),
            X86Register::YMM4 => UCX86Register(unicorn_engine::RegisterX86::YMM4),
            X86Register::YMM5 => UCX86Register(unicorn_engine::RegisterX86::YMM5),
            X86Register::YMM6 => UCX86Register(unicorn_engine::RegisterX86::YMM6),
            X86Register::YMM7 => UCX86Register(unicorn_engine::RegisterX86::YMM7),
            X86Register::YMM8 => UCX86Register(unicorn_engine::RegisterX86::YMM8),
            X86Register::YMM9 => UCX86Register(unicorn_engine::RegisterX86::YMM9),
            X86Register::YMM10 => UCX86Register(unicorn_engine::RegisterX86::YMM10),
            X86Register::YMM11 => UCX86Register(unicorn_engine::RegisterX86::YMM11),
            X86Register::YMM12 => UCX86Register(unicorn_engine::RegisterX86::YMM12),
            X86Register::YMM13 => UCX86Register(unicorn_engine::RegisterX86::YMM13),
            X86Register::YMM14 => UCX86Register(unicorn_engine::RegisterX86::YMM14),
            X86Register::YMM15 => UCX86Register(unicorn_engine::RegisterX86::YMM15),
            X86Register::YMM16 => UCX86Register(unicorn_engine::RegisterX86::YMM16),
            X86Register::YMM17 => UCX86Register(unicorn_engine::RegisterX86::YMM17),
            X86Register::YMM18 => UCX86Register(unicorn_engine::RegisterX86::YMM18),
            X86Register::YMM19 => UCX86Register(unicorn_engine::RegisterX86::YMM19),
            X86Register::YMM20 => UCX86Register(unicorn_engine::RegisterX86::YMM20),
            X86Register::YMM21 => UCX86Register(unicorn_engine::RegisterX86::YMM21),
            X86Register::YMM22 => UCX86Register(unicorn_engine::RegisterX86::YMM22),
            X86Register::YMM23 => UCX86Register(unicorn_engine::RegisterX86::YMM23),
            X86Register::YMM24 => UCX86Register(unicorn_engine::RegisterX86::YMM24),
            X86Register::YMM25 => UCX86Register(unicorn_engine::RegisterX86::YMM25),
            X86Register::YMM26 => UCX86Register(unicorn_engine::RegisterX86::YMM26),
            X86Register::YMM27 => UCX86Register(unicorn_engine::RegisterX86::YMM27),
            X86Register::YMM28 => UCX86Register(unicorn_engine::RegisterX86::YMM28),
            X86Register::YMM29 => UCX86Register(unicorn_engine::RegisterX86::YMM29),
            X86Register::YMM30 => UCX86Register(unicorn_engine::RegisterX86::YMM30),
            X86Register::YMM31 => UCX86Register(unicorn_engine::RegisterX86::YMM31),
            X86Register::ZMM0 => UCX86Register(unicorn_engine::RegisterX86::ZMM0),
            X86Register::ZMM1 => UCX86Register(unicorn_engine::RegisterX86::ZMM1),
            X86Register::ZMM2 => UCX86Register(unicorn_engine::RegisterX86::ZMM2),
            X86Register::ZMM3 => UCX86Register(unicorn_engine::RegisterX86::ZMM3),
            X86Register::ZMM4 => UCX86Register(unicorn_engine::RegisterX86::ZMM4),
            X86Register::ZMM5 => UCX86Register(unicorn_engine::RegisterX86::ZMM5),
            X86Register::ZMM6 => UCX86Register(unicorn_engine::RegisterX86::ZMM6),
            X86Register::ZMM7 => UCX86Register(unicorn_engine::RegisterX86::ZMM7),
            X86Register::ZMM8 => UCX86Register(unicorn_engine::RegisterX86::ZMM8),
            X86Register::ZMM9 => UCX86Register(unicorn_engine::RegisterX86::ZMM9),
            X86Register::ZMM10 => UCX86Register(unicorn_engine::RegisterX86::ZMM10),
            X86Register::ZMM11 => UCX86Register(unicorn_engine::RegisterX86::ZMM11),
            X86Register::ZMM12 => UCX86Register(unicorn_engine::RegisterX86::ZMM12),
            X86Register::ZMM13 => UCX86Register(unicorn_engine::RegisterX86::ZMM13),
            X86Register::ZMM14 => UCX86Register(unicorn_engine::RegisterX86::ZMM14),
            X86Register::ZMM15 => UCX86Register(unicorn_engine::RegisterX86::ZMM15),
            X86Register::ZMM16 => UCX86Register(unicorn_engine::RegisterX86::ZMM16),
            X86Register::ZMM17 => UCX86Register(unicorn_engine::RegisterX86::ZMM17),
            X86Register::ZMM18 => UCX86Register(unicorn_engine::RegisterX86::ZMM18),
            X86Register::ZMM19 => UCX86Register(unicorn_engine::RegisterX86::ZMM19),
            X86Register::ZMM20 => UCX86Register(unicorn_engine::RegisterX86::ZMM20),
            X86Register::ZMM21 => UCX86Register(unicorn_engine::RegisterX86::ZMM21),
            X86Register::ZMM22 => UCX86Register(unicorn_engine::RegisterX86::ZMM22),
            X86Register::ZMM23 => UCX86Register(unicorn_engine::RegisterX86::ZMM23),
            X86Register::ZMM24 => UCX86Register(unicorn_engine::RegisterX86::ZMM24),
            X86Register::ZMM25 => UCX86Register(unicorn_engine::RegisterX86::ZMM25),
            X86Register::ZMM26 => UCX86Register(unicorn_engine::RegisterX86::ZMM26),
            X86Register::ZMM27 => UCX86Register(unicorn_engine::RegisterX86::ZMM27),
            X86Register::ZMM28 => UCX86Register(unicorn_engine::RegisterX86::ZMM28),
            X86Register::ZMM29 => UCX86Register(unicorn_engine::RegisterX86::ZMM29),
            X86Register::ZMM30 => UCX86Register(unicorn_engine::RegisterX86::ZMM30),
            X86Register::ZMM31 => UCX86Register(unicorn_engine::RegisterX86::ZMM31),
            X86Register::R8B => UCX86Register(unicorn_engine::RegisterX86::R8B),
            X86Register::R9B => UCX86Register(unicorn_engine::RegisterX86::R9B),
            X86Register::R10B => UCX86Register(unicorn_engine::RegisterX86::R10B),
            X86Register::R11B => UCX86Register(unicorn_engine::RegisterX86::R11B),
            X86Register::R12B => UCX86Register(unicorn_engine::RegisterX86::R12B),
            X86Register::R13B => UCX86Register(unicorn_engine::RegisterX86::R13B),
            X86Register::R14B => UCX86Register(unicorn_engine::RegisterX86::R14B),
            X86Register::R15B => UCX86Register(unicorn_engine::RegisterX86::R15B),
            X86Register::R8D => UCX86Register(unicorn_engine::RegisterX86::R8D),
            X86Register::R9D => UCX86Register(unicorn_engine::RegisterX86::R9D),
            X86Register::R10D => UCX86Register(unicorn_engine::RegisterX86::R10D),
            X86Register::R11D => UCX86Register(unicorn_engine::RegisterX86::R11D),
            X86Register::R12D => UCX86Register(unicorn_engine::RegisterX86::R12D),
            X86Register::R13D => UCX86Register(unicorn_engine::RegisterX86::R13D),
            X86Register::R14D => UCX86Register(unicorn_engine::RegisterX86::R14D),
            X86Register::R15D => UCX86Register(unicorn_engine::RegisterX86::R15D),
            X86Register::R8W => UCX86Register(unicorn_engine::RegisterX86::R8W),
            X86Register::R9W => UCX86Register(unicorn_engine::RegisterX86::R9W),
            X86Register::R10W => UCX86Register(unicorn_engine::RegisterX86::R10W),
            X86Register::R11W => UCX86Register(unicorn_engine::RegisterX86::R11W),
            X86Register::R12W => UCX86Register(unicorn_engine::RegisterX86::R12W),
            X86Register::R13W => UCX86Register(unicorn_engine::RegisterX86::R13W),
            X86Register::R14W => UCX86Register(unicorn_engine::RegisterX86::R14W),
            X86Register::R15W => UCX86Register(unicorn_engine::RegisterX86::R15W),
            X86Register::IDTR => UCX86Register(unicorn_engine::RegisterX86::IDTR),
            X86Register::GDTR => UCX86Register(unicorn_engine::RegisterX86::GDTR),
            X86Register::LDTR => UCX86Register(unicorn_engine::RegisterX86::LDTR),
            X86Register::TR => UCX86Register(unicorn_engine::RegisterX86::TR),
            X86Register::FPCW => UCX86Register(unicorn_engine::RegisterX86::FPCW),
            X86Register::FPTAG => UCX86Register(unicorn_engine::RegisterX86::FPTAG),
            X86Register::MSR => UCX86Register(unicorn_engine::RegisterX86::MSR),
            X86Register::MXCSR => UCX86Register(unicorn_engine::RegisterX86::MXCSR),
            X86Register::FS_BASE => UCX86Register(unicorn_engine::RegisterX86::FS_BASE),
            X86Register::GS_BASE => UCX86Register(unicorn_engine::RegisterX86::GS_BASE),
            X86Register::FLAGS => UCX86Register(unicorn_engine::RegisterX86::FLAGS),
            X86Register::RFLAGS => UCX86Register(unicorn_engine::RegisterX86::RFLAGS),
            X86Register::FIP => UCX86Register(unicorn_engine::RegisterX86::FIP),
            X86Register::FCS => UCX86Register(unicorn_engine::RegisterX86::FCS),
            X86Register::FDP => UCX86Register(unicorn_engine::RegisterX86::FDP),
            X86Register::FDS => UCX86Register(unicorn_engine::RegisterX86::FDS),
            X86Register::FOP => UCX86Register(unicorn_engine::RegisterX86::FOP),
            X86Register::ENDING => UCX86Register(unicorn_engine::RegisterX86::ENDING),
            // all flag registers map to INVALID in unicorn
            _ => UCX86Register(unicorn_engine::RegisterX86::INVALID),
        }
    }
}

impl Deref for UCX86Register {
    type Target = unicorn_engine::RegisterX86;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl X86Register {
    pub fn size_bits(self) -> u8 {
        match self {
            X86Register::AL | X86Register::CL | X86Register::DL | X86Register::BL => 8,
            X86Register::AX | X86Register::CX | X86Register::DX | X86Register::BX => 16,
            X86Register::EAX
            | X86Register::ECX
            | X86Register::EDX
            | X86Register::EBX
            | X86Register::ESP
            | X86Register::EBP
            | X86Register::ESI
            | X86Register::EDI => 32,
            X86Register::RAX
            | X86Register::RCX
            | X86Register::RDX
            | X86Register::RBX
            | X86Register::RSP
            | X86Register::RBP
            | X86Register::RSI
            | X86Register::RDI
            | X86Register::R8
            | X86Register::R9
            | X86Register::R10
            | X86Register::R11
            | X86Register::R12
            | X86Register::R13
            | X86Register::R14
            | X86Register::R15 => 64,
            _ => 0,
        }
    }
}
